version: '3'

services:

  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: pytorch-jupyter-base:0.1

  server:
    image: pytorch-jupyter-base:0.1
    container_name: pytorch-jupyter-server
    volumes:
      - ./workspace:/home/jovyan/workspace
      - ./tutorials:/home/jovyan/tutorials
    ports:
      - "8888:8888"
